name: Deploy Deep-Dive demo API

on: [push]

jobs:
  API-Deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Deploy API
        env:
          APIM_USER: ${{ secrets.APIM_USER }}
          APIM_PASS: ${{ secrets.APIM_PASS }}
          APIM_HOST: ${{ secrets.APIM_HOST }}
          APIM_PORT: ${{ secrets.APIM_PORT }}
        run: mvn clean exec:java
#      - name: Install newman
#        run: sudo npm -g install newman
#      - name: Run API tests
#        run: |
#          sleep 1
#          newman run ./tests/AirportsAPI.postman_collection.json -e ./tests/RBI_Demo_Env.postman_environment.json --reporter-json-export output.json --insecure